### ISSUE TITLE
Broken. Needs revamp?

### ISSUE THREAD

**Issue by idkjs** [LXSMNSYC/scoped-model#24]
Is re-scoped-model broken per Readme? Or is it just the codesandbox build?

Seems package and example build locally.

Thank you, sir.

**Comment by LXSMNSYC** [comment]
Sorry for the late reply. I checked out the CI logs and it seems that the codesandbox build is broken, as Parcel cannot resolve the react library. I need to check this out, thank you!

**Comment by idkjs** [comment]
Nice. Well done, @LXSMNSYC
